FROM node:0.12
# Install gem sass for  grunt-contrib-sass

# Set development environment as default
ENV NODE_ENV development

# Port 3000 for server
# Port 35729 for livereload
EXPOSE 3000 35729
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
         && echo 'Asia/Shanghai' >/etc/timezone \